fprintf('Building mesh ...\n'); 
[nodes, elems, epsilon_r] = build_simple_mesh( ...
    'w_core',     w_core, ...
    'h_core',     h_core, ...
    'w_sim',      w_sim,   ...
    'h_sim',      h_sim,   ...
    'n_core',     n_core, ...
    'n_clad',     n_clad, ...
    'target_edge_length', wavelength/mesh_res,  ...
    'plot_mesh',  false);

fprintf('Nodes: %d,  Elements: %d\n', size(nodes,1), size(elems,1));

if plot_mesh ==1
    figure('Name', 'Mesh Visualization (Permittivity)', 'Color', 'w','Position', [200, 200, 1500, 500]);
    ph = patch('Faces', elems, 'Vertices', nodes, ...
               'FaceVertexCData', epsilon_r, ...
               'FaceColor', 'flat', ...
               'EdgeColor', 'k', ...
               'LineWidth', 0.1);
    % axis equal tight;
    xlabel('x [\mum]'); ylabel('y [\mum]');
    title('Zoomed in Mesh Material Distribution (\epsilon_r)');
    cb = colorbar;
    ylabel(cb, 'Relative Permittivity \epsilon_r');
    xlim([-w_core*1.2, w_core*1.2]); 
    ylim([-h_core*0.75, h_core*0.75]);
end