
%%  Element-constant colour plot using patch()
function tripcolor_patch(ax, nodes, elems, fvals)
    patch('Parent', ax, ...
          'Faces',           elems, ...
          'Vertices',        nodes, ...
          'FaceVertexCData', fvals(:), ...
          'FaceColor',       'flat', ...
          'EdgeColor',       'none');
    colormap(ax, 'hot');
end

